image: node:12.16

cache:
  untracked: true
  paths:
    - node_modules/

everything:
  script:
    - yarn
    - yarn test
    - yarn build-storybook
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
  only:
    - merge_requests
